INSERT INTO `birimler` VALUES (1, 1, 0, 0, 'Eğitim Fakültesi', 'Faculty of Education', '1', 6, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (2, 1, 1, 0, 'Okul Öncesi Öğretmenliği', 'Pre-School Education', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (3, 1, 2, 0, 'İngilizce Öğretmenliği', 'English Language Teaching', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (4, 1, 3, 0, 'Japonca Öğretmenliği', 'Japanese Language Teaching', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (5, 1, 4, 0, 'Sınıf Öğretmenliği', 'Primary School Education', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (6, 1, 5, 0, 'Beden Eğitimi ve Spor Öğretmenliği', 'Physical and Sports Education', '0', 7, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (7, 1, 6, 0, 'Coğrafya Öğretmenliği', 'Geography Education', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (8, 1, 10, 0, 'Tarih Öğretmenliği', 'History Education', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (9, 1, 11, 0, 'Türk Dili ve Edebiyatı Öğretmenliği', 'Turkish Language and Literature Education', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (10, 1, 14, 0, 'Almanca Öğretmenliği', 'German Language Teaching', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (11, 1, 15, 0, 'Sınıf Öğretmenliği (İ.Ö)', 'Primary School Education', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (12, 1, 16, 0, 'Türkçe Öğretmenliği', 'Turkish Language Teaching', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (13, 1, 17, 0, 'Türkçe Öğretmenliği (İ.Ö)', 'Turkish Language Teaching', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (14, 1, 18, 0, 'Okul Öncesi Öğretmenliği (İ.Ö)', 'Pre-School Education', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (15, 1, 20, 0, 'Resim İş Öğretmenliği', 'Arts and Crafts Education', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (16, 1, 22, 0, 'Bilgisayar ve Öğretim Teknolojileri Öğretmenliği', 'Computer Sciences and Teaching Tech. Education', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (17, 1, 23, 0, 'Bilgisayar ve Öğretim Teknolojileri Öğretmenliği (İ.Ö)', 'Computer Sciences and Teaching Tech. Education', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (18, 1, 24, 0, 'Fen Bilgisi Öğretmenliği', 'Science Education', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (19, 1, 25, 0, 'Fen Bilgisi Öğretmenliği (İ.Ö)', 'Science Education', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (20, 1, 26, 0, 'İngilizce Öğretmenliği (İ.Ö)', 'English Language Teaching', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (21, 1, 27, 0, 'Sosyal Bilgiler Öğretmenliği', 'Social Studies Education', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (22, 1, 28, 0, 'Müzik Öğretmenliği', 'Music Teaching', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (23, 1, 29, 0, 'Rehberlik ve Psikolojik Danışmanlık', 'Guidance and Psychological Counseling', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (24, 2, 0, 0, 'Fen Edebiyat Fakültesi', 'Faculty of Sciences and Arts', '1', 6, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (25, 2, 1, 0, 'Klasik Arkeoloji', 'Classical Archaelogy', '0', 7, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (26, 2, 2, 0, 'Sanat Tarihi', 'History of Art', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (27, 2, 3, 0, 'Biyoloji', 'Biology', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (28, 2, 3, 3, 'Moleküler Biyoloji ve Mikrobiyoloji', 'Moleculer Biology & Microbiology', '1', 8, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (29, 2, 3, 2, 'Botanik ve Ekoloji', 'Botany & Ecology', '1', 8, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (30, 2, 3, 1, 'Zooloji ve Ekoloji', 'Zoology & Ecology', '1', 8, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (31, 2, 4, 0, 'Coğrafya', 'Geography', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (32, 2, 5, 0, 'Fizik', 'Physics', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (33, 2, 6, 0, 'İngiliz Dili ve Edebiyatı', 'English Language and Literature', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (34, 2, 7, 0, 'Kimya', 'Chemistry', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (35, 2, 8, 0, 'Matematik', 'Mathematics', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (36, 2, 9, 0, 'Tarih', 'History', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (37, 2, 10, 0, 'Türk Dili ve Edebiyatı', 'Turkish Language and Literature', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (38, 2, 11, 0, 'Tarih (İ.Ö)', 'History (Evening Program)', '1', 7, 'tum', '1', '1');
INSERT INTO `birimler` VALUES (39, 2, 12, 0, 'Türk Dili ve Edebiyatı (İ.Ö)', 'Turkish Language and Literature (Evening Program)', '1', 7, 'tum', '1', '1');
INSERT INTO `birimler` VALUES (40, 2, 13, 2, 'Botonik ve Ekoloji', 'Botany & Ecology', '1', 8, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (41, 2, 13, 1, 'Zooloji ve Ekoloji', 'Zoology & Ecology', '1', 8, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (42, 2, 13, 0, 'Biyoloji (İ.Ö)', 'Biology (Evening Program)', '1', 7, 'tum', '1', '1');
INSERT INTO `birimler` VALUES (43, 2, 13, 3, 'Moleküler Biyoloji ve Mikrobiyoloji', 'Moleculer Biology & Microbiology', '1', 8, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (44, 2, 14, 0, 'Fizik (İ.Ö)', 'Physics (Evening Program)', '1', 7, 'tum', '1', '1');
INSERT INTO `birimler` VALUES (45, 2, 15, 0, 'Arkeoloji', 'Archaelogy', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (46, 2, 16, 0, 'Matematik (İ.Ö)', 'Mathematics (Evening Program)', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (47, 2, 17, 0, 'Sosyoloji', 'Sociology', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (48, 2, 18, 0, 'Coğrafya (İ.Ö.)', 'Geograpy (S.E.)', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (49, 2, 19, 0, 'Felsefe', 'Philosophy', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (50, 2, 20, 0, 'Moleküler Biyoloji ve Genetik', 'Molecular Biology and Genetics', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (51, 3, 0, 0, 'İlahiyat Fakültesi', 'Faculty of Theology', '1', 6, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (52, 3, 1, 0, 'İlahiyat', 'Theology', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (53, 3, 2, 0, 'İlahiyat (İ.Ö.)', 'Theology (S.E.)', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (54, 4, 0, 0, 'Mühendislik Fakültesi', 'Faculty of Engineering', '1', 6, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (55, 4, 1, 0, 'Bilgisayar Mühendisliği', 'Computer Engineering', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (56, 4, 2, 0, 'Gıda Mühendisliği', 'Food Engineering', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (57, 4, 3, 0, 'Jeoloji Mühendisliği', 'Geological Engineering', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (58, 4, 4, 0, 'Jeofizik Mühendisliği', 'Geophysical Engineering', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (59, 4, 5, 0, 'Çevre Mühendisliği', 'Environmental Engineering', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (60, 4, 6, 0, 'Şehir ve Bölge Planlama', 'Urban and Regional Planning Department', '0', 7, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (61, 4, 7, 0, 'Mimarlık', 'Department of Architecture', '0', 7, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (62, 4, 8, 0, 'İnşaat Mühendisliği', 'Department of Civil Engineering', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (63, 4, 9, 0, 'Endüstri Mühendisliği', 'Department of Industrial Engineering', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (64, 4, 10, 0, 'Geomatik Mühendisliği', 'Geomatic Engineering', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (65, 5, 0, 0, 'Su Ürünleri Fakültesi', 'Faculty of Fish and Fisheries', '1', 6, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (66, 5, 1, 3, 'Avlama ve İşleme Teknolojisi', 'Department of fisheries and processing technology', '0', 8, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (67, 5, 1, 2, 'Yetiştiricilik', 'Department of Aquaculture', '0', 8, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (68, 5, 1, 0, 'Su Ürünleri ', 'Fisheries', '0', 7, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (69, 5, 2, 0, 'Su Ürünleri  (İ.Ö)', 'Fisheries (Evening Program)', '0', 7, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (70, 5, 3, 0, 'Su Ürünleri Mühendisliği', 'Fisheries Engineering', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (71, 5, 4, 0, 'Su Ürünleri Mühendisliği (İ.Ö)', 'Fisheries Engineering (Evening Program)', '1', 7, 'tum', '1', '1');
INSERT INTO `birimler` VALUES (72, 6, 0, 0, 'Ziraat Fakültesi', 'Faculty of Agriculture', '1', 6, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (73, 6, 3, 0, 'Bitkisel Üretim', 'Plant Production', '0', 7, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (74, 6, 3, 3, 'Tarla Bitkileri', 'Field Crops', '0', 8, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (75, 6, 3, 2, 'Bitki Koruma', 'Plant Protection', '0', 8, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (76, 6, 3, 1, 'Bahçe Bitkileri', 'Horticulture', '0', 8, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (77, 6, 4, 0, 'Hayvansal Üretim', 'Animal Production', '0', 7, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (78, 6, 4, 1, 'Zootekni', 'Animal Production', '0', 8, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (79, 6, 5, 2, 'Tarımsal Yapılar ve Sulama', 'Agricultural Constraction and Irrigation', '0', 8, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (80, 6, 5, 1, 'Tarım Makinaları', 'Agricultural Mechanisation', '0', 8, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (81, 6, 5, 4, 'Tarım Ekonomisi', 'Agricultural Economics', '0', 8, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (82, 6, 5, 0, 'Tarım Teknolojisi', 'Agriculture Technology', '0', 7, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (83, 6, 5, 3, 'Toprak', 'Soil Science', '0', 8, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (84, 6, 6, 5, 'Tarım Makinaları', 'Agricultural Mechanisation', '0', 8, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (85, 6, 6, 1, 'Bahçe Bitkileri', 'Horticulture', '1', 8, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (86, 6, 6, 8, 'Zootekni', 'Animal Production', '1', 8, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (87, 6, 6, 4, 'Tarımsal Yapılar ve Sulama', 'Agricultural Constraction and Irrigation', '1', 8, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (88, 6, 6, 0, 'Ziraat Mühendisliği', 'Agriculture Engineering', '0', 7, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (89, 6, 6, 7, 'Toprak', 'Soil Science', '1', 8, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (90, 6, 6, 3, 'Tarım Ekonomisi', 'Agricultural Economics', '1', 8, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (91, 6, 6, 6, 'Tarla Bitkileri', 'Field Crops', '1', 8, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (92, 6, 6, 2, 'Bitki Koruma', 'Plant Protection', '1', 8, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (93, 6, 7, 0, 'Peyzaj Mimarlığı', 'Landscape Arcitecture', '0', 7, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (94, 6, 8, 0, 'Bahçe Bitkileri', 'Horticulture', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (95, 6, 9, 0, 'Bitki Koruma', 'Plant Protection', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (96, 6, 10, 0, 'Tarım Ekonomisi', 'Agricultural Economy', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (97, 6, 11, 0, 'Tarım Makineleri', 'Agricultural Mechanisation', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (98, 6, 12, 0, 'Tarla Bitkileri', 'Field Crops', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (99, 6, 13, 0, 'Toprak Bilimi ve Bitki Besleme', 'Soil Science and Plant Nutrition', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (100, 6, 14, 0, 'Zootekni', 'Animal Production', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (101, 6, 15, 0, 'Tarımsal yapılar ve sulama', 'Agricultural Buildings and Irrıgation', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (102, 6, 16, 0, 'Tarımsal Biyoteknoloji', 'Agricultural Biotechnology', '1', 1, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (103, 7, 0, 0, 'Biga İktisadi ve İdari Bilimler Fakültesi', 'Faculty of Economics & Admin.Sciences at BIGA', '1', 6, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (104, 7, 1, 0, 'İktisat', 'Economics', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (105, 7, 2, 0, 'İşletme', 'Business Studies', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (106, 7, 3, 0, 'Çalışma Ekonomisi ve Endüstri İlişkileri', 'Labour Economics and Industrial Relations', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (107, 7, 4, 0, 'Kamu Yönetimi', 'Public Manage', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (108, 7, 5, 0, 'Maliye', 'Public Finance', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (109, 7, 6, 0, 'Uluslararası İlişkiler', 'International Relations', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (110, 7, 7, 0, 'İktisat (İ.Ö)', 'Economics (Evening Program)', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (111, 7, 8, 0, 'İşletme (İ.Ö)', 'Business Studies (Evening Program)', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (112, 7, 9, 0, 'Çalışma Ekonomisi ve Endüstri İlişkileri (İ.Ö)', 'Labour Economics and Industrial Relations (Evening Prg)', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (113, 7, 10, 0, 'Kamu Yönetimi (İ.Ö)', 'Public Management (Evening Program)', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (114, 7, 11, 0, 'Maliye (İ.Ö)', 'Public Finance (Evening Program)', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (115, 7, 12, 0, 'Uluslararası İlişkiler (İ.Ö)', 'International Relations (Evening Program)', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (116, 7, 13, 0, 'Ekonometri', 'Econometrics', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (117, 7, 14, 0, 'Ekonometri (İ.Ö)', 'Econometrics (S.E.)', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (118, 8, 0, 0, 'Turizm İşletmeciliği ve Otelcilik Y.O.', 'Vocational School of Tourism & Hotel Management', '1', 9, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (119, 8, 1, 0, 'Turizm İşletmeciliği', 'Tourism Management', '0', 10, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (120, 8, 2, 0, 'Konaklama İşletmeciliği', 'Accommodation Management', '1', 10, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (121, 8, 3, 0, 'Seyahat İşletmeciliği', 'Travel Management', '0', 10, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (122, 8, 4, 0, 'Konaklama İşletmeciliği (İ.Ö.)', 'Accommodation Management (Evening Prog.)', '1', 10, 'tum', '1', '1');
INSERT INTO `birimler` VALUES (123, 8, 5, 0, 'Seyahat İşletmeciliği ve Turizm Rehberliği', 'Travel Management and Tourism Guidance', '1', 10, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (124, 9, 0, 0, 'Çanakkale Teknik Bilimler Meslek Yüksek Okulu', 'Çanakkale Vocational School of Technical Sciences', '1', 12, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (130, 9, 3, 0, 'İnşaat', 'Building Construction', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (132, 9, 5, 0, 'Bilgisayarlı Muhasebe ve Vergi Uygulama', '', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (133, 9, 7, 0, 'Grafik', 'Graphics', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (134, 9, 8, 0, 'Bilgisayar Programcılığı', 'Computer Programming', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (135, 9, 9, 0, 'Fotoğrafçılık', 'Photography', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (136, 9, 10, 0, 'İnşaat (İ.Ö)', 'Building Construction (Evening Program)', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (138, 9, 12, 0, 'Bilgisayarlı Muhasebe ve Vergi Uygulama (İ.Ö)', '', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (139, 9, 13, 0, 'El Sanatları', '', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (145, 9, 15, 2, 'İletim Dağıtım ve Tesisat Dalı', 'Branch of Transmission Distribition and Instlalation', '1', 14, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (146, 9, 15, 1, 'Fabrika Bakım ve İmalat Dalı', 'Branch of Factory Maintenance and Manufacture', '1', 14, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (147, 9, 15, 0, 'Elektrik (İ.Ö)', 'Electricty (Evening Program)', '1', 13, 'tum', '1', '1');
INSERT INTO `birimler` VALUES (148, 9, 16, 4, 'Trikotaj Dalı', 'Knitting', '0', 14, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (149, 9, 16, 0, 'Tekstil (İ.Ö)', 'Textile (Evening Program)', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (150, 9, 16, 7, 'Kalite Kontrol Dalı', 'Quality Control', '0', 14, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (151, 9, 16, 3, 'Örme Dalı', 'Manufacture of Thread', '0', 14, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (152, 9, 16, 6, 'Tekstil Terbiyesi Dalı', 'Textile Pedagogy', '0', 14, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (153, 9, 16, 2, 'Dokuma Dalı', 'Weaving', '0', 14, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (154, 9, 16, 5, 'Konfeksiyon Dalı', 'Branch of Confection', '0', 14, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (155, 9, 16, 1, 'İplikçilik Dalı', 'Confection', '0', 14, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (156, 9, 17, 3, 'Talaşsız Şekillendirme ve Kaynak Teknolojileri Dalı', 'Branch of Sawdustless Shaping & Welding Technologies', '0', 14, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (157, 9, 17, 2, 'Bilgisayarlı Tasarım ve Üretim Dalı', 'Computer-Assisted Design and Production Branch', '0', 14, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (158, 9, 17, 1, 'Üretim Dalı', 'Branch of Production', '1', 14, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (159, 9, 17, 4, 'Fabrika Bakım Dalı', 'Factory Maintenance Branch', '1', 14, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (160, 9, 17, 0, 'Makine (İ.Ö)', 'Machine (Evening Program)', '1', 13, 'tum', '1', '1');
INSERT INTO `birimler` VALUES (161, 9, 18, 0, 'Mobilya ve Dekorasyon (İ.Ö)', 'Furnishings (Evening Program)', '1', 13, 'tum', '1', '1');
INSERT INTO `birimler` VALUES (162, 9, 19, 1, 'Finansman Dalı', 'Financing', '0', 14, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (164, 9, 19, 2, 'Yönetim Dalı', 'Branch of Management', '0', 14, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (166, 9, 21, 0, 'Bilgisayar Teknolojisi ve Programlama', 'Computer Technology and Programming', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (168, 9, 23, 2, 'Yönetim Dalı', 'Branch of Management', '0', 14, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (169, 9, 23, 1, 'Finansman Dalı', 'Financing', '0', 14, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (171, 9, 24, 0, 'Bilgisayar Teknolojisi ve Programlama (İ.Ö)', 'Computer Technology and Programming (Evening Prog)', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (172, 33, 3, 0, 'Çocuk Gelişimi (İ.Ö)', 'Child Development (Evening Program)', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (173, 9, 26, 0, 'Gemi İnşaatı', 'Ship Construction', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (174, 9, 27, 0, 'Fotoğrafçılık ve Kameramanlık', 'Photography and Filming', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (175, 9, 28, 0, 'Bilgisayar Programcılığı', 'Computer Programming', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (176, 9, 29, 0, 'Bilgisayar Programcılığı (İ.Ö)', 'Computer Programming (Evening Program)', '1', 13, 'tum', '1', '1');
INSERT INTO `birimler` VALUES (177, 9, 30, 0, 'Grafik Tasarımı', 'Graphic Design', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (178, 33, 4, 0, 'Halkla İlişkiler ve Tanıtım', 'Public Relations and Publicity', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (179, 9, 32, 0, 'İnşaat Teknolojisi', 'Constraction Technology', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (180, 9, 33, 0, 'İnşaat Teknolojisi (İ.Ö)', 'Constraction Technology (Evening Program)', '1', 13, 'tum', '1', '1');
INSERT INTO `birimler` VALUES (181, 33, 5, 0, 'İşletme Yönetimi', 'Business Administration', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (182, 33, 6, 0, 'İşletme Yönetimi (İ.Ö)', 'Business Administration (Evening Program)', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (183, 33, 7, 0, 'Muhasebe ve Vergi Uygulamaları', 'Accounting and Tax', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (184, 33, 8, 0, 'Muhasebe ve Vergi Uygulamaları (İ.Ö)', 'Accounting and Tax (Evening Program)', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (185, 9, 38, 0, 'Tekstil Teknolojisi (İ.Ö)', 'Textile Technologies (Evening Program)', '1', 13, 'tum', '1', '1');
INSERT INTO `birimler` VALUES (186, 33, 9, 0, 'Yerel Yönetimler', 'Local Authority', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (187, 33, 1, 0, 'Büro Yönetimi ve Yönetici Asistanlığı', 'Office Management and Secretaryship', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (188, 33, 2, 0, 'Büro Yönetimi ve Yönetici Asistanlığı (İ.Ö)', 'Office Management and Secretaryship (S.E.)', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (189, 9, 42, 0, 'Giyim Üretim Teknolojisi', 'Textile Technology', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (190, 33, 10, 0, 'Yerel Yönetimler (İ.Ö)', 'Local Authority (S.E.)', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (191, 10, 0, 0, 'Biga Meslek Yüksekokulu', 'Biga Vocational College', '1', 12, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (192, 10, 1, 0, 'Elektrik', 'Electricity Technology', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (193, 10, 1, 2, 'İletim Dağıtım ve Tesisat Dalı', 'Branch of Transmission Distribition and Installation', '0', 14, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (194, 10, 1, 1, 'Fabrika Bakım ve İmalat Dalı', 'Branch of Factory Maintenance and Manufacture', '1', 14, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (195, 10, 2, 0, 'Otomotiv', 'Motor Mechanics', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (196, 10, 3, 0, 'Bilgisayarlı Muhasebe ve Vergi Uygulama', '', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (197, 10, 4, 0, 'Seracılık', 'Greenhouse Production', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (198, 10, 5, 0, 'Dericilik', 'Leatherworking', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (199, 10, 6, 0, 'Süt ve Ürünleri', 'Milk and Milk Products', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (200, 10, 7, 0, 'Muhasebe (İ.Ö)', 'Accounting (Evening Program)', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (201, 10, 8, 0, 'Dericilik (İ.Ö)', 'Leatherworking (Evening Program)', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (202, 10, 9, 0, 'Süt ve Ürünleri (İ.Ö)', 'Milk and Milk Products (Evening Program)', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (203, 10, 10, 0, 'Muhasebe', 'Accounting', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (204, 10, 11, 0, 'Kooperatifçilik', 'Cooperatives Management', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (205, 10, 12, 0, 'Otomotiv (İ.Ö)', 'Motor Mechanics (Evening Program)', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (206, 10, 13, 0, 'Hayvan Yetiştiriciliği ve Sağlığı', 'Animal Breeding and Animal Health', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (207, 10, 14, 0, 'Makine', 'Machinery', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (208, 10, 14, 1, 'Üretim Dalı', 'Production Branch', '1', 14, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (209, 10, 15, 0, 'Mobilya ve Dekorasyon', 'Furniture and Decoration', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (210, 10, 16, 1, 'Reklam Yönetimi', '', '1', 14, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (211, 10, 16, 0, 'Pazarlama', 'Marketing', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (212, 10, 16, 2, 'Satış Yönetimi', '', '1', 14, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (213, 10, 17, 0, 'Büyük ve Küçük Baş Hayvan Yetiştiriciliği', 'Cattle and Small Ruminant Breeding', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (214, 10, 19, 0, 'Deri Teknolojisi', 'Leather Technology', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (215, 10, 20, 0, 'Deri Teknolojisi (İ.Ö)', 'Leather Technology (Evening Program)', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (216, 10, 21, 0, 'Muhasebe ve Vergi Uygulamaları', 'Accounting and Tax', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (217, 10, 22, 0, 'Muhasebe ve Vergi Uygulamaları (İ.Ö)', 'Accounting and Tax (Evening Program)', '1', 13, 'tum', '1', '1');
INSERT INTO `birimler` VALUES (218, 10, 23, 0, 'Otomotiv Teknolojisi', 'Automotive Technology', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (219, 10, 24, 0, 'Otomotiv Teknolojisi (İ.Ö)', 'Automotive Technology (Evening Program)', '1', 13, 'tum', '1', '1');
INSERT INTO `birimler` VALUES (220, 10, 25, 0, 'Pazarlama (İ.Ö)', 'Marketing (Evening Program)', '1', 13, 'tum', '1', '1');
INSERT INTO `birimler` VALUES (221, 10, 26, 0, 'Süt ve Ürünleri Teknolojisi', 'Milk and Dairy Product Technology', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (222, 10, 27, 0, 'Süt ve Ürünleri Teknolojisi (İ.Ö)', 'Milk and Dairy Product Technology (Evening Prog.)', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (223, 10, 28, 0, 'İşletme Yönetimi', 'Bussiness Adminstration', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (224, 10, 29, 0, 'Gıda Teknolojisi', 'Food Technology', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (225, 10, 30, 0, 'Yerel Yönetimler', 'Local Authority', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (226, 11, 0, 0, 'Çanakkale Sağlık Hizmetleri Meslek Yüksekokulu', 'Health Services Vocational College', '1', 12, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (227, 11, 3, 0, 'Ambulans ve Acil Bakım Teknikerliği', 'Ambulance and Emergency Treatment Technician', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (228, 11, 4, 0, 'Tıbbi Laboratuvar', 'Medical Laboratory Assistant', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (229, 11, 5, 0, 'Radyoloji', 'Radiology', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (230, 11, 6, 0, 'Paramedik', 'Paramedic', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (231, 11, 7, 0, 'Tıbbi Görüntüleme Teknikleri', 'Medical Scanning Technology', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (232, 11, 8, 0, 'Tıbbi Laboratuvar Teknikleri', 'Medical Laboratory Technics', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (233, 11, 9, 0, 'İlk ve Acil Yardım', 'First Aid and Emergency', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (234, 12, 0, 0, 'Ayvacık Meslek Yüksekokulu', 'Ayvacık Vocational School', '1', 12, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (235, 12, 2, 0, 'Halıcılık', 'Carpetmaking', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (236, 12, 3, 0, 'Halıcılık ve Desinatörlüğü', 'Carpetmarking and Desination', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (237, 12, 4, 1, 'Finansman Dalı', 'Financing', '0', 14, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (238, 12, 4, 0, 'İşletme', 'Business Studies', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (239, 12, 4, 2, 'Yönetim Dalı', 'Branch of Management', '0', 14, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (240, 12, 5, 0, 'Turizm ve Otel İşletmeciliği', 'Tourism and Hotel Management', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (241, 12, 5, 2, 'Yiyecek -İçecek ve Mutfak Dalı', 'Food & Beverage - Kitchen', '1', 14, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (242, 12, 5, 1, 'Önbüro ve Kat Hizmetleri', 'Front Office-Housekeeping', '0', 14, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (243, 12, 6, 0, 'İşletme (İ.Ö)', 'Business Studies (Evening Program)', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (244, 12, 6, 1, 'Finansman Dalı', 'Financing', '0', 14, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (245, 12, 7, 0, 'Halıcılık ve Desinatörlüğü (İ.Ö)', 'Carpetmarking and Desination (Evening Program)', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (246, 12, 8, 0, 'Ağırlama Hizmetleri', 'Catering', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (247, 12, 9, 0, 'Halıcılık ve Kilimcilik', 'Carpet and Rug Producing', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (248, 12, 10, 0, 'Halıcılık ve Kilimcilik (İ.Ö)', 'Carpet and Rug Producing (Evening Program)', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (249, 12, 11, 0, 'İşletme Yönetimi', 'Business Adminstration', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (250, 12, 12, 0, 'İşletme Yönetimi (İ.Ö)', 'Business Adminstration (Evening Program)', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (251, 12, 13, 0, 'Bankacılık ve Sigortacılık', 'Banking and Insurance', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (252, 12, 14, 0, 'Bankacılık ve Sigortacılık (İ.Ö.)', 'Banking and Insurance (S.E.)', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (253, 12, 15, 0, 'Turizm ve Otel İşletmeciliği (İ.Ö)', 'Tourism and Hotel Management (S.E.)', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (254, 13, 0, 0, 'Bayramiç Meslek Yüksekokulu', 'Bayramiç Vocational College', '1', 12, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (255, 13, 1, 0, 'Bağcılık', '', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (256, 13, 2, 0, 'Meyve Sebze İşleme', '', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (257, 13, 3, 2, 'Reklamcılık', 'Advertisement', '0', 14, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (258, 13, 3, 1, 'Satış Yönetimi', 'Marketing Management', '1', 14, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (259, 13, 3, 0, 'Pazarlama', 'Marketing', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (260, 13, 4, 0, 'Bahçe Ziraatı', 'Horticulture', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (261, 13, 5, 0, 'Gıda Teknolojisi', 'Food Technology', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (262, 13, 6, 0, 'Bahçe Ziraatı (İ.Ö)', 'Horticulture (Evening Program)', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (263, 13, 7, 0, 'Gıda Teknolojisi (İ.Ö)', 'Food Technology (Evening Program)', '1', 13, 'tum', '1', '1');
INSERT INTO `birimler` VALUES (264, 13, 8, 0, 'Pazarlama (İ.Ö)', 'Marketing (Evening Program)', '1', 13, 'tum', '1', '1');
INSERT INTO `birimler` VALUES (265, 13, 8, 2, 'Reklamcılık', '', '0', 14, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (266, 13, 8, 1, 'Satış Yönetimi', 'Marketing Management', '1', 14, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (267, 13, 9, 0, 'Bahçe Tarımı', 'Horticulture', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (268, 13, 10, 0, 'Bahçe Tarımı (İ.Ö)', 'Horticulture (Evening Program)', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (269, 13, 11, 0, 'Tohumculuk', 'Seed Production', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (270, 14, 0, 0, 'Çan Meslek Yüksekokulu', 'Çan Vocational College', '1', 12, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (271, 14, 2, 0, 'Seramik', 'Ceramics', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (272, 14, 3, 0, 'Teknik Seramik', 'Technical Ceramics', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (273, 14, 4, 0, 'Endüstriyel Seramik', 'Industrial Ceramics', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (274, 14, 5, 0, 'e-Ticaret', 'e-Commerce', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (275, 14, 6, 0, 'Lojistik', 'Logistics', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (276, 14, 7, 0, 'Mekatronik', 'Mechatronics', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (277, 14, 8, 0, 'Mekatronik (İ.Ö)', 'Mechatronics (Evening Program)', '1', 13, 'tum', '1', '1');
INSERT INTO `birimler` VALUES (278, 14, 9, 0, 'Endüstriyel Cam ve Seramik', 'Industrial Glass and Ceramic', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (279, 14, 10, 0, 'Lojistik (İ.Ö)', 'Logistics (Evening Program)', '1', 13, 'tum', '1', '1');
INSERT INTO `birimler` VALUES (280, 14, 11, 0, 'Maden Teknolojisi', 'Mining Technology', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (281, 14, 12, 0, 'Pazarlama', 'Marketing', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (282, 14, 13, 0, 'Seramik, Cam ve Çinicilik', 'Ceramics, Glass and Tile', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (283, 14, 14, 0, 'Elektronik Teknolojisi', 'Electronics Technology', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (284, 14, 15, 0, 'Maden Teknolojisi (İ.Ö)', 'Mining Technology (S.E.)', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (285, 14, 16, 0, 'Muhasebe ve Vergi Uygulamaları', 'Accounting and Tax', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (286, 14, 17, 0, 'Elektrik Enerjisi Üretim, İletim ve Dağıtım', 'Electric Power Gen.,Transmission and Dist.', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (287, 15, 0, 0, 'Ezine Meslek Yüksekokulu', 'Ezine Vocational College', '1', 12, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (288, 15, 1, 0, 'İşletmecilik', '', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (289, 15, 2, 0, 'Bilgisayarlı Muhasebe ve Vergi Uygulama', 'Computer Based Accounting and Tax', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (290, 15, 3, 0, 'Bilgisayarlı Muhasebe ve Vergi Uygulama (İ.Ö)', '', '0', 13, 'tum', '0', '1');
INSERT INTO `birimler` VALUES (291, 15, 4, 0, 'İşletmecilik (İ.Ö)', '', '0', 13, 'tum', '0', '1');
INSERT INTO `birimler` VALUES (292, 15, 5, 1, 'Finansman Dalı', 'Financing', '0', 14, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (293, 15, 5, 0, 'İşletme', 'Business Studies', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (294, 15, 5, 2, 'Yönetim Dalı', 'Branch of Management', '0', 14, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (295, 15, 6, 0, 'Muhasebe', 'Accounting', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (296, 15, 7, 0, 'Muhasebe (İ.Ö)', 'Accounting (Evening Program)', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (297, 15, 8, 0, 'İşletme (İ.Ö)', 'Business Studies (Evening Program)', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (298, 15, 8, 2, 'Yönetim Dalı', 'Branch of Management', '1', 14, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (299, 15, 8, 1, 'Finansman Dalı', 'Financing', '1', 14, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (300, 15, 9, 2, 'Reklamcılık', 'Advertisement', '0', 14, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (301, 15, 9, 1, 'Satış Yönetimi', 'Marketing Management', '1', 14, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (302, 15, 9, 0, 'Pazarlama', 'Marketing', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (303, 15, 10, 0, 'İşletme Yönetimi', 'Business Administration', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (304, 15, 11, 0, 'İşletme Yönetimi (İ.Ö)', 'Business Administration (Evening Program)', '1', 13, 'tum', '1', '1');
INSERT INTO `birimler` VALUES (305, 15, 12, 0, 'Muhasebe ve Vergi Uygulamaları', 'Accounting and Tax', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (306, 15, 13, 0, 'Muhasebe ve Vergi Uygulamaları (İ.Ö)', 'Accounting and Tax (Evening Program)', '1', 13, 'tum', '1', '1');
INSERT INTO `birimler` VALUES (307, 15, 14, 0, 'Pazarlama (İ.Ö)', 'Marketing (Evening Program)', '1', 13, 'tum', '1', '1');
INSERT INTO `birimler` VALUES (308, 15, 15, 0, 'Dış Ticaret', 'Foreign Commerce', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (309, 15, 16, 0, 'Halkla İlişkiler ve Tanıtım', 'Public Relations and Publicity', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (310, 16, 0, 0, 'Gelibolu Piri Reis Meslek Yüksekokulu', 'Gelibolu Piri Reis Vocational College', '1', 12, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (311, 16, 1, 0, 'Bilgisayarlı Muhasebe ve Vergi Uygulama', '', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (312, 16, 2, 0, 'Turizm ve Otelcilik', 'Tourism and Hotel Management', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (313, 16, 3, 0, 'Gemi Makineleri İşletme', 'Shipping Machinory Management', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (314, 16, 4, 0, 'Muhasebe (İ.Ö)', 'Accounting (Evening Program)', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (315, 16, 5, 2, 'Yiyecek-İçecek ve Mutfak Dalı', 'Food & Beverage - Kitchen', '1', 14, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (316, 16, 5, 1, 'Önbüro ve Kat Hizmetleri', 'Front Office-Housekeeping', '1', 14, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (317, 16, 5, 0, 'Turizm ve Otel İşletmeciliği (İ.Ö)', 'Tourism and Hotel Management (Evening Program)', '1', 13, 'tum', '1', '1');
INSERT INTO `birimler` VALUES (318, 16, 6, 0, 'Muhasebe', 'Accounting', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (319, 16, 7, 2, 'Yiyecek-İçecek ve Mutfak Dalı', 'Food & Beverage - Kitchen', '1', 14, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (320, 16, 7, 1, 'Önbüro ve Kat Hizmetleri', 'Front Office-Housekeeping', '1', 14, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (321, 16, 7, 0, 'Turizm ve Otel İşletmeciliği', 'Tourism and Hotel Management', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (322, 16, 8, 0, 'Gemi Makineleri', 'Shipping Machinery', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (323, 16, 9, 0, 'Deniz ve Liman İşletme', 'Port Management', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (324, 16, 10, 0, 'Ağırlama Hizmetleri', 'Catering', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (325, 16, 11, 0, 'Ağırlama Hizmetleri (İ.Ö)', 'Catering (Evening Program)', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (326, 16, 12, 0, 'Muhasebe ve Vergi Uygulamaları', 'Accounting and Tax', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (327, 16, 13, 0, 'Muhasebe ve Vergi Uygulamaları (İ.Ö)', 'Accounting and Tax (Evening Program)', '1', 13, 'tum', '1', '1');
INSERT INTO `birimler` VALUES (328, 16, 14, 0, 'Deniz ve Liman İşletmeciliği', 'Port Management', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (329, 17, 0, 0, 'Yenice Meslek Yüksekokulu', 'Yenice Vocational College', '1', 12, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (330, 17, 1, 0, 'El Sanatları', 'Handicrafts', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (331, 17, 2, 0, 'Bilgisayarlı Muhasebe ve Vergi Uygulama', '', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (332, 17, 3, 2, 'Yönetim Dalı', 'Branch of Management', '0', 14, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (333, 17, 3, 1, 'Finansman Dalı', 'Financing', '0', 14, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (334, 17, 3, 0, 'İşletme', 'Business Studies', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (335, 17, 4, 0, 'Muhasebe', 'Accounting', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (336, 17, 5, 2, 'Yönetim Dalı', 'Branch of Management', '0', 14, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (337, 17, 5, 1, 'Finansman Dalı', 'Financing', '0', 14, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (338, 17, 5, 0, 'İşletme (İ.Ö)', 'Business Studies (Evening Program)', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (339, 17, 6, 0, 'Muhasebe (İ.Ö)', 'Accounting (Evening Program)', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (340, 17, 7, 2, 'Sigorta Dalı', 'Branch of Isurance', '0', 14, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (341, 17, 7, 1, 'Bankacılık Dalı', 'Branch of Banking', '1', 14, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (342, 17, 7, 0, 'Bankacılık ve Sigortacılık', 'Banking and Isurance', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (343, 17, 8, 1, 'Bankacılık Dalı', 'Branch of Banking', '1', 14, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (344, 17, 8, 0, 'Bankacılık ve Sigortacılık (İ.Ö)', 'Banking and Isurance', '1', 13, 'tum', '1', '1');
INSERT INTO `birimler` VALUES (345, 17, 9, 1, 'Konfeksiyon', 'Ready-Made Clothing', '0', 14, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (346, 17, 9, 0, 'Tekstil', 'Textile', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (347, 17, 10, 0, 'Dış Ticaret ve Avrupa Birliği', 'Foreign Commerce and European Union', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (348, 17, 11, 0, 'Dış Ticaret', 'Foreign Commerce', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (349, 17, 12, 0, 'Dış Ticaret (İ.Ö)', 'Foreign Commerce (Evening Program)', '1', 13, 'tum', '1', '1');
INSERT INTO `birimler` VALUES (350, 17, 13, 0, 'Geleneksel El Sanatları', 'Traditional Handicraft', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (351, 17, 14, 0, 'İşletme Yönetimi', 'Business Administration', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (352, 17, 15, 0, 'İşletme Yönetimi (İ.Ö)', 'Business Administration (Evening Program)', '1', 13, 'tum', '1', '1');
INSERT INTO `birimler` VALUES (353, 17, 16, 0, 'Muhasebe ve Vergi Uygulamaları', 'Accounting and Tax', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (354, 17, 17, 0, 'Muhasebe ve Vergi Uygulamaları (İ.Ö)', 'Accounting and Tax (Evening Program)', '1', 13, 'tum', '1', '1');
INSERT INTO `birimler` VALUES (355, 17, 18, 0, 'Tekstil Teknolojisi', 'Textile Technology', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (356, 17, 19, 0, 'Lojistik', 'Logistics', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (357, 17, 20, 0, 'Pazarlama', 'Marketing', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (358, 18, 0, 0, 'Çanakkale Sağlık Yüksekokulu', 'Çanakkale School of Health', '1', 9, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (359, 18, 1, 0, 'Ebelik', 'Midwifery', '1', 10, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (360, 18, 2, 0, 'Hemşirelik', 'Nursing', '1', 10, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (361, 18, 3, 0, 'Acil Yardım ve Afet Yönetimi', 'Rescue and Emergency Management', '1', 10, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (362, 18, 4, 0, 'Acil Yardım ve Afet Yönetimi (İ.Ö.)', 'Rescue and Emergency Management (S.E.)', '1', 10, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (806, 19, 5, 2, 'İktisat (Doktora)', 'Economics (PhD)', '1', 5, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (805, 19, 5, 1, 'İktisat Anabilim D.(Y.Lisans)', 'Economics (Master)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (804, 19, 5, 0, 'İktisat ABD.', 'Economics', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (803, 19, 4, 4, 'Kamu Yönetimi (Y.Lisans Tezsiz)(İ.Ö.)', 'Public Administration (Taught Master)(SE)', '1', 4, 'tum', '1', '1');
INSERT INTO `birimler` VALUES (802, 19, 4, 3, 'Kamu Yönetimi (Y.Lisans Tezsiz)', 'Public Administration (Taught Master)', '1', 4, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (801, 19, 4, 2, 'Kamu Yönetimi (Doktora)', 'Public Administration (PhD)', '1', 5, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (799, 19, 4, 0, 'Kamu Yönetimi ABD.', 'Public Administration', '1', 2, 'tum', '1', '1');
INSERT INTO `birimler` VALUES (800, 19, 4, 1, 'Kamu Yönetimi (Y.Lisans)', 'Public Administration (Thesis)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (798, 19, 3, 1, 'Maliye (Y.Lisans)', 'Public Finance (Master)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (797, 19, 3, 0, 'Maliye Anabilim Dalı', 'Public Finance', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (796, 19, 2, 1, 'Çalışma Eko.& Endüstri İlişkileri (Y.Lisans)', 'Labour Economics & Industrial Relations (Master)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (795, 19, 2, 0, 'Çalışma Eko.& Endüstri İlişkileri ABD.', 'Labour Economics & Industrial Relations', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (794, 19, 1, 4, 'İşletme (Y.Lisans Tezsiz)(İ.Ö.)', 'Business Studies (Taught Master)(SE)', '1', 4, 'tum', '1', '1');
INSERT INTO `birimler` VALUES (793, 19, 1, 3, 'İşletme (Y.Lisans Tezsiz)', 'Business Studies (Taught Master)', '1', 4, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (792, 19, 1, 2, 'İşletme (Doktora)', 'Business Studies (PhD)', '1', 5, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (790, 19, 1, 0, 'İşletme Anabilim Dalı', 'Business Studies', '1', 2, 'tum', '1', '1');
INSERT INTO `birimler` VALUES (791, 19, 1, 1, 'İşletme (Y.Lisans)', 'Business Studies (Master)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (789, 19, 0, 0, 'Sosyal Bilimler Enstitüsü', 'Social Studies Institute', '1', 1, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (788, 21, 32, 1, 'Uzay Bilimleri ve Tekn.(Y.lisans)', 'Space Science and Tech.(Master)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (787, 21, 32, 0, 'Uzay Bilimleri ve Tekn.', 'Space Science and Tech.', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (786, 21, 31, 1, 'Çevre Mühendisliği (Y.lisans)', 'Environmental Engineering (Master)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (785, 21, 31, 0, 'Çevre Mühendisliği', 'Environmental Engineering', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (784, 21, 21, 2, 'Su Ürünleri (Doktora)', 'Fisheries (PhD)', '1', 5, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (782, 21, 21, 0, 'Su Ürünleri', 'Fisheries', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (783, 21, 21, 1, 'Su Ürünleri (Y.lisans)', 'Fisheries (Master)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (781, 21, 20, 1, 'Jeofizik Mühendisliği (Y.lisans)', 'Geophysical Engineering (Master)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (780, 21, 20, 0, 'Jeofizik Mühendisliği', 'Geophysical Engineering', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (779, 21, 19, 2, 'Jeoloji Mühendisliği (Doktora)', 'Geological Engineering (PhD)', '1', 5, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (778, 21, 19, 1, 'Jeoloji Mühendisliği (Y.lisans)', 'Geological Engineering (Master)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (777, 21, 19, 0, 'Jeoloji Mühendisliği', 'Geological Engineering', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (776, 21, 18, 1, 'Tarım Ekonomisi (Y.lisans)', 'Agricultural Economics (Master)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (775, 21, 18, 0, 'Tarım Ekonomisi', 'Agricultural Economics', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (774, 21, 17, 1, 'Tarım Makineleri (Y.lisans)', 'Agricultural Mechanisation (Master)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (773, 21, 17, 0, 'Tarım Makineleri', 'Agricultural Mechanisation', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (772, 21, 16, 2, 'Su Ürünleri Avlama ve İşleme Tek.(Doktora)', 'Mar.Scie.-Fishering & Processing Tech.(PhD)', '1', 5, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (771, 21, 16, 1, 'Su Ürünleri Avlama ve İşleme Tek.(Y.lisans)', 'Mar.Scie.-Fishering & Processing Tech.(Master)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (770, 21, 16, 0, 'Su Ürünleri Avlama ve İşleme Teknolojisi', 'Mar.Scie.-Fishering & Processing Tech.', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (768, 21, 15, 0, 'Peyzaj Mimarlığı', 'Landscape Architecture', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (769, 21, 15, 1, 'Peyzaj Mimarlığı (Y.lisans)', 'Landscape Architecture (Master)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (767, 21, 14, 1, 'Tarımsal Yapılar ve Sulama (Y.lisans)', 'Agricultural Const.& Irrigation (Master)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (765, 21, 13, 2, 'Gıda Mühendisliği (Doktora)', 'Food Engineering (PhD)', '1', 5, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (766, 21, 14, 0, 'Tarımsal Yapılar ve Sulama', 'Agricultural Constraction & Irrigation', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (764, 21, 13, 1, 'Gıda Mühendisliği (Y.lisans)', 'Food Engineering (Master)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (763, 21, 13, 0, 'Gıda Mühendisliği', 'Food Engineering', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (762, 21, 12, 2, 'Bahçe Bitkileri (Doktora)', 'Horticulture (PhD)', '1', 5, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (412, 20, 0, 0, 'Gökçeada Meslek Yüksekokulu', 'Gökçeada Vocational College', '1', 12, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (413, 20, 1, 0, 'İşletmecilik', '', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (414, 20, 2, 0, 'Turizm İşletmeciliği', '', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (415, 20, 3, 0, 'Halkla İlişkiler ve Reklamcılık', 'Public Relations and Advertising', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (416, 20, 4, 0, 'Bilgisayar Teknolojisi ve Programlama (İ.Ö)', 'Computer Technology and Programming (Evening Pr)', '0', 13, 'tum', '0', '1');
INSERT INTO `birimler` VALUES (417, 20, 5, 1, 'Finansman Dalı', 'Financing', '0', 14, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (418, 20, 5, 0, 'İşletme', 'Business Studies', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (419, 20, 5, 2, 'Yönetim Dalı', 'Branch of Management', '0', 14, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (420, 20, 6, 2, 'Yiyecek-İçecek ve Mutfak Dalı', 'Food & Beverage - Kitchen', '1', 14, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (421, 20, 6, 1, 'Önbüro ve Kat Hizmetleri', 'Front Office-Housekeeping', '0', 14, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (422, 20, 6, 0, 'Turizm ve Otel İşletmeciliği', 'Tourism and Hotel Management', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (423, 20, 7, 0, 'Dış Ticaret ve Avrupa Birliği', 'Foreign Trade and European Union', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (424, 20, 8, 0, 'Halkla İlişkiler ve Reklamcılık (İ.Ö)', 'Public Relations and Advertising (Evening Program)', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (425, 20, 9, 1, 'Finansman Dalı', 'Financing', '0', 14, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (426, 20, 9, 0, 'İşletme (İ.Ö)', 'Business Studies (Evening Program)', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (427, 20, 9, 2, 'Yönetim Dalı', 'Branch of Management', '0', 14, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (428, 20, 10, 0, 'Turizm ve Seyahat İşletmeciliği', 'Tourism and Travel Management', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (429, 20, 11, 0, 'Ağırlama Hizmetleri', 'Catering', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (430, 20, 12, 0, 'Dış Ticaret', 'Foreign Commerce', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (431, 20, 13, 0, 'Halkla İlişkiler ve Tanıtım', 'Public Relations and Publicity', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (432, 20, 14, 0, 'Halkla İlişkiler ve Tanıtım (İ.Ö)', 'Public Relations and Publicity (Evening Program)', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (433, 20, 15, 0, 'İşletme Yönetimi', 'Business Administration', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (434, 20, 16, 0, 'İşletme Yönetimi (İ.Ö)', 'Business Administration (Evening Program)', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (435, 20, 17, 0, 'Turizm ve Seyahat Hizmetleri', 'Tourism and Travelling Service', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (436, 20, 18, 0, 'Turizm ve Seyahat Hizmetleri  (İ.Ö.)', 'Tourism and Travelling Service (Evening Program)', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (761, 21, 12, 1, 'Bahçe Bitkileri (Y.lisans)', 'Horticulture (Master)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (760, 21, 12, 0, 'Bahçe Bitkileri', 'Horticulture', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (759, 21, 11, 2, 'Bitki Koruma (Doktora)', 'Plant Protection (PhD)', '1', 5, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (758, 21, 11, 1, 'Bitki Koruma (Y.lisans)', 'Plant Protection (Master)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (757, 21, 11, 0, 'Bitki Koruma', 'Plant Protection', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (756, 21, 10, 1, 'Bilgisayar Mühendisliği (Y.lisans)', 'Computer Engineering (Master)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (755, 21, 10, 0, 'Bilgisayar Mühendisliği', 'Computer Engineering', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (754, 21, 9, 2, 'Toprak (Doktora)', 'Soil Science (PhD)', '1', 5, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (753, 21, 9, 1, 'Toprak (Y.lisans)', 'Soil Science (Master)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (752, 21, 9, 0, 'Toprak', 'Soil Science', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (751, 21, 8, 2, 'Zootekni (Doktora)', 'Animal Production (PhD)', '1', 5, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (750, 21, 8, 1, 'Zootekni (Y.lisans)', 'Animal Science (Master)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (749, 21, 8, 0, 'Zootekni', 'Animal Science', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (748, 21, 7, 2, 'Su Ürünleri Temel Bilimleri (Doktora)', 'Marine Sciences-Basic Sciences (PhD)', '1', 5, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (747, 21, 7, 1, 'Su Ürünleri Temel Bilimleri (Y.lisans)', 'Marine Sciences-Basic Sciences (Master)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (746, 21, 7, 0, 'Su Ürünleri Temel Bilimleri', 'Marine Sciences-Basic Sciences', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (745, 21, 6, 2, 'Su Ürünleri Yetiştiriciliği (Doktora)', 'Marine Sciences-Cultuvation (PhD)', '1', 5, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (744, 21, 6, 1, 'Su Ürünleri Yetiştiriciliği (Y.lisans)', 'Marine Sciences-Cultuvation (Master)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (743, 21, 6, 0, 'Su Ürünleri Yetiştiriciliği', 'Marine Sciences-Cultuvation', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (742, 21, 5, 2, 'Tarla Bitkileri (Doktora)', 'Field Crops (PhD)', '1', 5, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (741, 21, 5, 1, 'Tarla Bitkileri (Y.lisans)', 'Field Crops (Master)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (740, 21, 5, 0, 'Tarla Bitkileri', 'Field Crops', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (739, 21, 4, 2, 'Biyoloji (Doktora)', 'Biology (PhD)', '1', 5, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (738, 21, 4, 1, 'Biyoloji (Y.lisans)', 'Biology (Master)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (737, 21, 4, 0, 'Biyoloji', 'Biology', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (736, 21, 3, 2, 'Kimya (Doktora)', 'Chemistry (PhD)', '1', 5, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (735, 21, 3, 1, 'Kimya (Y.lisans)', 'Chemistry (Master)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (734, 21, 3, 0, 'Kimya', 'Chemistry', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (733, 21, 2, 2, 'Fizik (doktora)', 'Physics (PhD)', '1', 5, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (732, 21, 2, 1, 'Fizik (Y.lisans)', 'Physics (Master)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (731, 21, 2, 0, 'Fizik', 'Physics', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (730, 21, 1, 2, 'Matematik (Doktora)', 'Mathematics (PhD)', '1', 5, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (729, 21, 1, 1, 'Matematik (Y.lisans)', 'Mathematics (Master)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (728, 21, 1, 0, 'Matematik', 'Mathematics', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (727, 21, 0, 0, 'Fen Bilimleri Enstitüsü', 'Natural and Applied Sciences Institute', '1', 1, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (488, 22, 0, 0, 'Güzel Sanatlar Fakültesi', 'Faculty of Fine Arts', '1', 6, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (489, 22, 1, 0, 'Resim', 'Painting', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (490, 22, 2, 0, 'Seramik', 'Ceramics', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (491, 22, 3, 0, 'Eski Çini Onarımları', 'Ancient Tile Repair', '0', 7, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (492, 22, 4, 0, 'Grafik Tasarımı', 'Graphic Design', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (493, 22, 5, 0, 'Oyunculuk', 'Acting', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (494, 22, 6, 0, 'Sinema ve Televizyon', 'Cinema and Television', '0', 7, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (495, 22, 7, 0, 'Tekstil Tasarımı', 'Textiles Design', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (496, 23, 0, 0, 'Lapseki Meslek Yüksekokulu', 'Lapseki Vocational College', '1', 12, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (497, 23, 1, 0, 'Fidan ve Fidecilik', 'Seedling and Nursery Production', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (498, 23, 2, 0, 'Tarım Ürünlerinin Muhafazası ve Depolanması', 'Post-Harvest Technology', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (499, 23, 3, 0, 'Muhasebe', 'Accounting', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (500, 23, 4, 0, 'Organik Tarım', 'Organic Agriculture', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (501, 23, 5, 0, 'Bahçe Tarımı', 'Horticulture', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (502, 23, 6, 0, 'Muhasebe ve Vergi Uygulamaları', 'Accounting and Tax', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (503, 23, 7, 0, 'Tarımsal Ürünler Muhafaza ve Depolama Teknolojisi', 'Agricultural Products Protecting and Granary Technology', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (504, 24, 0, 0, 'Tıp Fakültesi', 'Faculty of Medicine', '1', 6, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (505, 24, 1, 0, 'Tıp Fakültesi', 'Faculty of Medicine', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (506, 25, 0, 0, 'Beden Eğitimi ve Spor Yüksekokulu', 'School of Physical Education and Sports', '1', 9, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (507, 25, 1, 0, 'Spor Yöneticiliği', 'Sports Management', '1', 10, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (508, 25, 2, 0, 'Antrenörlük Eğitimi', 'Coaching Education', '1', 10, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (509, 25, 3, 0, 'Beden Eğitimi ve Spor Öğretmenliği', 'Physical Education Teacher Training', '1', 10, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (510, 26, 0, 0, 'Gökçeada Uygulamalı Bilimler Y.O.', 'Gökçeada School of Applied Sciences', '1', 9, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (511, 26, 1, 0, 'Balıkçılık Teknolojisi', 'Fisheries Technology', '1', 10, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (512, 26, 2, 0, 'Gastronomi', 'Gastronomy', '1', 10, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (513, 26, 3, 0, 'Kültürel Miras Yönetimi', 'Cultural Heritage Management', '1', 10, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (514, 26, 4, 0, 'Organik Tarım İşletmeciliği', 'Organic Agriculture', '1', 10, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (515, 26, 5, 0, 'Turizm İşletmeciliği', 'Tourism Management', '1', 10, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (516, 26, 6, 0, 'Restorasyon ve Konservasyon', 'Restoration and Conservation', '1', 10, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (517, 27, 0, 0, 'Yabancı Diller Yüksekokulu', 'School of Foreign Languages', '1', 9, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (518, 28, 0, 0, 'Konservatuar', 'Conservatory', '1', 9, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (519, 29, 0, 0, 'Eğitim Bilimleri Enstitüsü', 'Institute of Educational Sciences', '1', 1, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (520, 30, 0, 0, 'Sağlık Bilimleri Enstitüsü', 'Institute of Health Sciences', '1', 1, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (522, 31, 0, 0, 'İletişim Fakültesi', 'Faculty of Communication', '1', 6, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (523, 500, 0, 0, 'Araştırma ve Uygulama Merkezleri', 'Research and Training Centers', '1', 15, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (524, 500, 2, 0, 'Astrofizik Araştırma Merkezi - Ulupınar Gözlem Evi', 'Astrophysics Research Center - Ulupınar Observatory', '1', 15, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (525, 500, 3, 0, 'Sürekli Eğitim Merkezi', 'Continuing Education Center', '1', 15, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (526, 500, 4, 0, 'Çanakkale Seramikleri Arş. ve Uyg. Merkezi', 'Çanakkale Ceramics & Development Research and Training Center', '1', 15, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (527, 500, 5, 0, 'Yabancı Dil Eğitimi Uygulama ve Araştırma Merkezi', 'Foreign Language Teaching Research and Training Center', '1', 15, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (528, 500, 6, 0, 'Uzaktan Algılama Araştırma ve Uygulama Merkezi', 'Remote Sensing Research and Training Center', '1', 15, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (529, 500, 7, 0, 'El Sanatları Uygulama ve Araştırma Merkezi', 'Handicrafts Research and Training Center', '1', 15, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (530, 500, 8, 0, 'Bilim ve Teknoloji Uygulama Merkezi', 'Scientific Technology Training Center', '1', 15, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (531, 500, 9, 0, 'Uygulama ve Araştırma Hastanesi', '', '1', 15, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (532, 500, 10, 0, 'Çevre Sorunları Araştırma ve Uygulama Merkezi', '', '1', 15, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (533, 500, 11, 0, 'İbrahim Bodur Girişimcilik Uygulama ve Araştırma Merkezi', '', '1', 15, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (534, 500, 12, 0, 'Su Altı Araştırma ve Uygulama Merkezi', '', '1', 15, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (535, 500, 13, 0, 'Enerji Kaynakları Araştırma ve Uygulama Merkezi', '', '1', 15, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (536, 500, 14, 0, 'Stratejik Araştırmalar Merkezi', '', '1', 15, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (537, 500, 15, 0, 'Süt ve Süt Ürünleri Uygulama ve Araştırma Merkez', '', '1', 15, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (538, 500, 16, 0, 'Deniz Kablumbağaları Uygulama ve Araştırma Merkezi', '', '1', 15, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (539, 500, 17, 0, 'Kadın Çalışmaları Uygulama ve Araştırma Merkezi', '', '1', 15, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (540, 500, 18, 0, 'Atatürk İlkeleri ve İnkılâp Tarihi Arş. ve Uyg. Merkezi', '', '1', 15, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (541, 500, 19, 0, 'Botanik Bahçesi ve Herbaryum Uyg. ve Arş.Merkezi', '', '1', 15, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (542, 500, 20, 0, 'Nanobilim ve Teknoloji Arş. ve Uyg. Merkezi', '', '1', 15, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (543, 500, 21, 0, 'Türkiye-Avustralya Çalışmaları Uyg. ve Arş. Merkezi', '', '1', 15, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (544, 500, 22, 0, 'Uzaktan Eğitim Uyg. ve Arş. Merkezi', '', '1', 15, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (545, 501, 0, 0, 'Rektörlüğe Bağlı Bölümler', 'Departments Attached to The Rector''s Office', '1', 16, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (546, 501, 1, 0, 'Atatürk İlkeleri ve İnkilap Tarihi Bölüm Başkanlığı', 'Atatürk''s Principles & History of the Turkish Republic', '1', 16, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (547, 501, 2, 0, 'Türk Dili Bölüm Başkanlığı', 'Turkish Language', '1', 16, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (548, 501, 3, 0, 'Beden eğitimi Bölüm Başkanlığı', 'Physical Education and Sport', '1', 16, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (549, 501, 4, 0, 'Güzel Sanatlar Bölüm Başkanlığı', 'Fine Arts', '1', 16, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (550, 501, 5, 0, 'Yabancı Diller Bölüm Başkanlığı', 'Foreign Languages', '1', 16, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (551, 501, 6, 0, 'Enformatik Bölüm Başkanlığı', 'Informatics', '1', 16, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (552, 502, 0, 0, 'İdari Birimler', 'Administrative Units', '1', 17, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (553, 502, 1, 0, 'Genel Sekreterlik', 'General Secretariat', '1', 17, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (554, 502, 2, 0, 'Personel Daire Başkanlığı', 'Personnel Affairs', '1', 17, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (555, 502, 3, 0, 'Öğrenci İşleri Daire Başkanlığı', 'Students Affairs', '1', 17, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (556, 502, 4, 0, 'Strateji Geliştirme Daire Başkanlığı', 'Strategy Development', '1', 17, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (557, 502, 5, 0, 'Sağlık Kültür Spor Daire Başkanlığı', 'Health, Culture and Sports', '1', 17, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (558, 502, 6, 0, 'Kütüphane ve Dökümantasyon Daire Başkanlığı', 'Library and Documentation', '1', 17, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (559, 502, 7, 0, 'Yapı İşleri ve Teknik Daire Başkanlığı', 'Construction and Technical Works', '1', 17, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (560, 502, 8, 0, 'Bilgi İşlem Daire Başkanlığı', 'Information Technology', '1', 17, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (561, 502, 9, 0, 'Dış İlişkiler Koordinatörlüğü', 'International Relations Office', '1', 17, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (562, 502, 10, 0, 'Uluslararası Araştırma ve Destek Birimi', 'International Research Support Unit', '1', 17, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (563, 502, 11, 0, 'Basın Halkla İlişkiler Birimi', 'Public Relations and Press Office', '1', 17, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (564, 502, 12, 0, 'Döner Sermaye İşletmesi Müdürlüğü', 'Revolving Fund Directorate', '1', 17, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (565, 502, 13, 0, 'İdari ve Mali İşler Dairesi Başkanlığı', 'Administrative and Financial Affairs Department', '1', 17, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (566, 502, 14, 0, 'Hukuk Müşavirliği', 'Law Consultancy', '1', 17, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (568, 500, 1, 0, 'Atatürk ve Çanakkale Savaşları Arş. Merkezi', 'Atatürk & the Gallipoli Campaign Research Center', '1', 15, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (569, 502, 15, 0, 'Rektörlük', 'Rectorate', '1', 17, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (569, 502, 16, 0, 'İç Hizmetler Müdürlüğü (Soförler Odası)', '', '1', 20, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (570, 700, 0, 0, 'Ana Güvenlik Kapısı', 'Main Security Gate', '1', 19, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (571, 999, 0, 0, 'Bilinmeyen', '', '1', 20, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (574, 22, 8, 0, 'Çini', 'Tile', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (575, 23, 8, 0, 'Laboratuvar Teknolojisi', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (576, 23, 9, 0, 'Bitki Koruma', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (577, 23, 10, 0, 'Maliye', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (578, 23, 11, 0, 'Fidan Yetiştiriciliği', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (579, 23, 12, 0, 'Laboratuvar Teknolojisi (İ.Ö)', '', '1', 13, 'tum', '1', '1');
INSERT INTO `birimler` VALUES (581, 4, 11, 0, 'Malzeme Bilimi ve Mühendisliği', 'Material Science And Engineering', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (582, 2, 21, 0, 'Uzay Bilimleri ve Teknolojileri  ', '', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (583, 2, 22, 0, 'Psikoloji', '', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (585, 2, 23, 0, 'İstatistik', '', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (586, 2, 24, 0, 'Doğu Dilleri ve Edebiyatları', '', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (587, 3, 3, 0, 'İlköğretim Din Kültürü ve Ahlak Bilgisi Öğretmeliği', '', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (589, 9, 44, 0, 'Şarap Üretimi', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (590, 10, 31, 0, 'Süt ve Besi Hayvancılığı (İ.Ö.)', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (591, 10, 32, 0, 'Büro Hizmetleri ve Yönetici Asistanlığı ', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (592, 10, 33, 0, 'Çocuk Gelişimi', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (593, 10, 34, 0, 'Gıda Teknolojisi (İ.Ö.)', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (594, 10, 35, 0, 'İşletme Yönetimi (İ.Ö.) ', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (595, 10, 36, 0, 'Süt ve Besi Hayvancılığı', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (596, 10, 37, 0, 'Kimya', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (597, 11, 10, 0, 'Anestezi ', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (598, 11, 11, 0, 'Perfüzyon Teknikler', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (599, 11, 12, 0, 'Elektronörofizyoloji', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (600, 11, 13, 0, 'Tibbi Görüntüleme Teknikleri (İ.Ö.)', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (601, 11, 14, 0, 'İlk ve Acil Yardım (İ.Ö.) ', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (602, 12, 16, 0, 'Turist Rehberliği ', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (604, 12, 17, 0, 'Aşçılık', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (605, 12, 18, 0, 'Geleneksel El Sanatları', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (606, 13, 12, 0, 'Su Ürünleri ', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (607, 13, 13, 0, 'Halkla İlişkiler ve Tanıtım ', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (608, 13, 14, 0, 'Çocuk Gelişimi', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (609, 13, 15, 0, 'Ormancılık ve Orman Ürünleri', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (610, 13, 16, 0, 'Ormancılık ve Orman Ürünleri (İ.Ö.)', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (611, 13, 17, 0, 'Halkla İlişkiler ve Tanıtım (İ.Ö.)   ', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (612, 14, 18, 0, 'Kuyumculuk ve Takı Tasarımı', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (613, 14, 19, 0, 'Mimari Dekoratif Sanatlar', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (614, 14, 20, 0, 'Sondaj Teknolojisi ', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (615, 14, 21, 0, 'Elektronik Teknolojisi (İ.Ö.)', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (617, 14, 22, 0, 'Enerji Tesisleri İşletmeciliği', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (618, 14, 23, 0, 'Biyomedikal Cihaz Teknolojisi', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (619, 14, 24, 0, 'Bilgisayar Programcılığı ', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (620, 14, 25, 0, 'Alternatif Enerji Kaynakları Teknolojisi', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (621, 15, 17, 0, 'Gıda Teknolojisi', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (622, 15, 18, 0, 'Turizm ve Seyahat Hizmetleri', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (623, 15, 19, 0, 'Turizm ve Seyahat Hizmetleri (İ.Ö)', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (624, 15, 20, 0, 'Süt Ürünleri', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (625, 15, 21, 0, 'Bankacılık ve Sigortacılık', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (626, 16, 15, 0, 'Turizm ve Seyahat Hizmetleri', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (627, 16, 16, 0, 'Turizm Rehberliği ', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (628, 16, 17, 0, 'Deniz ve Liman İşletmeciliği (İ.Ö.)  ', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (629, 16, 18, 0, 'Yat İşletme ve Yönetimi ', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (630, 16, 19, 0, 'İnsan Kaynakları ve Yönetimi  ', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (633, 16, 20, 0, 'Aşçılık ', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (634, 16, 21, 0, 'Deniz Ulaştırma ve İşletme', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (635, 17, 21, 0, 'Süt ve Ürünleri Teknolojisi ', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (636, 17, 22, 0, 'Ormancılık ve Orman Ürünleri', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (637, 17, 23, 0, 'Lojistik (İ.Ö.)', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (638, 17, 24, 0, 'Moda Tasarımı', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (639, 18, 5, 0, 'Sağlık Kurumları Yönetimi ', '', '1', 10, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (640, 20, 19, 0, 'Dış Ticaret (İ.Ö)', '', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (641, 20, 20, 0, 'Turizm ve Otel İşletmeciliği (İ.Ö)', '', '0', 13, 'tum', '0', '0');
INSERT INTO `birimler` VALUES (642, 23, 13, 0, 'Peyzaj ve Süs Bitkileri', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (643, 23, 14, 0, 'Tıbbi ve Aromatik Bitkiler ', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (644, 23, 15, 0, 'Bankacılık ve Sigortacılık ', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (645, 23, 16, 0, 'Maliye (İ.Ö.)', '', '1', 13, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (646, 25, 4, 0, 'Rekreasyon', '', '1', 10, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (647, 27, 1, 0, 'Hazırlık Eğitimi', '', '1', 10, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (648, 27, 2, 0, 'Mütercim Tercümanlık', '', '1', 10, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (649, 28, 1, 0, 'Çalgı', '', '1', 10, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (650, 28, 2, 0, 'Ses', '', '1', 10, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (651, 31, 1, 0, 'Radyo, Televizyon ve Sinema', 'Radio, Television and Cinema', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (652, 31, 2, 0, 'Halkla İlişkiler ve Reklamcılık ', '', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (653, 31, 3, 0, 'Görsel İletişim Tasarımı ', '', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (654, 31, 4, 0, 'Gazetecilik', '', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (655, 31, 5, 0, 'Yeni Medya', '', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (656, 31, 6, 0, 'İletişim Bilimleri', '', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (657, 32, 0, 0, 'Uygulamalı Bilimler Yüksekokulu', '', '1', 9, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (658, 32, 1, 0, 'Bankacılık ve Finans', '', '1', 10, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (660, 32, 2, 0, 'Uluslararası Ticaret ve Lojistik', '', '1', 10, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (661, 34, 0, 0, 'Mimarlık ve Tasarım Fakültesi', 'Faculty of Architecture & Design', '1', 6, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (662, 34, 1, 0, 'Peyzaj Mimarlığı', 'Landscape Arcitecture', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (664, 34, 2, 0, 'Şehir ve Bölge Planlama', 'Urban and Regional Planning Department', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (665, 34, 3, 0, 'Mimarlık', 'Department of Architecture', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (666, 35, 0, 0, 'İktisadi ve İdari Bilimler Fakültesi', '', '1', 6, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (667, 35, 1, 0, 'Siyaset Bilimi ve Kamu Yönetimi', '', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (668, 35, 2, 0, 'Ekonometri', '', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (669, 35, 3, 0, 'Çalışma Ekonomisi ve Endüstri İlişkileri ', '', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (670, 35, 4, 0, 'İşletme', '', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (671, 35, 5, 0, 'Maliye', '', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (672, 35, 6, 0, 'İktisat', '', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (673, 35, 7, 0, 'Uluslararası İlişkiler', '', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (674, 35, 8, 0, 'Yönetim Bilişim Sistemleri', '', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (675, 35, 9, 0, 'Uluslararası Ticaret ve Finansman', '', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (676, 35, 10, 0, 'Sağlık Yönetimi', '', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (677, 35, 11, 0, 'Sosyal Hizmet', '', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (679, 4, 12, 0, 'Jeofizik Mühendisliği (İ.Ö.)', 'Geophysical Engineering (S.E.)', '1', 7, 'tum', '1', '1');
INSERT INTO `birimler` VALUES (681, 4, 13, 0, 'Maden Mühendisliği', 'Mining Engineering', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (683, 4, 14, 0, 'Biyomühendislik', 'Bioengineering', '1', 7, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (684, 33, 0, 0, 'Çanakkale Sosyal Bilimler Meslek Yüksekokulu', 'Çanakkale Vocational School of Social Sciences', '1', 12, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (685, 29, 1, 0, 'Eğitim Bilimleri', '', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (686, 29, 2, 0, 'Güzel Sanatlar Eğitimi', '', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (687, 29, 3, 0, 'İlköğretim', '', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (688, 29, 4, 0, 'Ortaöğr.Sosyal Alanlar Eğt.', '', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (689, 29, 5, 0, 'Türkçe Eğitimi', '', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (690, 29, 6, 0, 'Yabancı Diller Eğitimi', '', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (691, 29, 7, 0, 'Bilgisayar ve Öğretim Teknolojileri', '', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (692, 29, 8, 0, 'Fen Bilgisi Eğitimi', '', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (693, 29, 9, 0, 'Ortaöğr.Fen ve Mat.Alan.Eğit.', '', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (694, 29, 1, 1, 'Eğitim Yönetimi ve Denetimi (Y.lisans)', '', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (695, 29, 1, 2, 'Eğitim Programları ve Öğretimi (Y.lisans)', '', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (696, 29, 1, 3, 'Eğitim Yön.,Tef.,Plan.& Ekonomisi (Y.lisans Tezsiz)(İ.Ö)', '', '1', 4, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (697, 29, 1, 4, 'Eğitim Bilimleri (doktora)', '', '1', 5, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (698, 29, 1, 5, 'Eğitim Bil.-Eğitim Yön.ve Denetimi (doktora)', '', '1', 5, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (699, 29, 2, 1, 'Resim-İş Eğitimi (Y.lisans)', '', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (700, 29, 3, 1, 'İlköğretim-Sınıf Öğretmenliği (Y.lisans)', '', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (701, 29, 3, 2, 'İlköğretim-Okul Öncesi Eğitim (Y.lisans)', '', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (702, 29, 4, 1, 'Coğrafya Eğitimi (Y.lisans)', '', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (703, 29, 4, 2, 'Tarih Eğitimi (Y.lisans)', '', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (704, 29, 4, 3, 'Türk Dili ve Ede.Eğt. (Y.lisans)', '', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (705, 29, 4, 4, 'Coğrafya Eğitimi (Y.lisans Tezsiz)', '', '1', 4, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (706, 29, 4, 5, 'Tarih Eğitimi (Y.lisans Tezsiz)', '', '1', 4, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (707, 29, 4, 6, 'Türk Dili ve Ede.Eğt. (Y.lisans Tezsiz)', '', '1', 4, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (708, 29, 5, 1, 'Türkçe Eğitimi (Y.lisans)', '', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (709, 29, 5, 2, 'Türkçe Eğitimi (doktora)', '', '1', 5, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (710, 29, 5, 3, 'Yabancı Dil Olarak Türkçenin Öğretimi (Y.lisans)', '', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (711, 29, 6, 1, 'Alman Dili Eğitimi (Y.lisans)', '', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (712, 29, 6, 2, 'İngiliz Dili Eğitimi (Y.lisans)', '', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (713, 29, 6, 3, 'İngiliz Dili Eğitimi (doktora)', '', '1', 5, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (714, 29, 7, 1, 'Bilgisayar ve Öğretim Teknolojileri (Y.lisans)', '', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (715, 29, 8, 1, 'Fen Bilgisi Eğitimi (Y.lisans)', '', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (716, 29, 9, 1, 'Fizik Öğretmenliği(Y.lisans Tezsiz)', '', '1', 4, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (717, 29, 9, 2, 'Kimya Öğretmenliği(Y.lisans Tezsiz)', '', '1', 4, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (718, 29, 9, 3, 'Biyoloji Öğretmenliği(Y.lisans Tezsiz)', '', '1', 4, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (719, 29, 9, 4, 'Matematik Öğretmenliği(Y.lisans Tezsiz)', '', '1', 4, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (721, 30, 1, 0, 'Beden Eğitimi ve Spor ABD', 'Division of Physical Education ', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (722, 30, 1, 1, 'Beden Eğitimi ve Spor Öğretmenliği (Tezli y.lisans)', 'Physical Education Teacher Training (Master with Thesis)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (723, 30, 2, 0, 'Fizyoloji ABD', 'Division of Fizyology', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (724, 30, 2, 1, 'Fizyoloji (Tezli Y.lisans)', 'Fizyology  (Master with Thesis)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (725, 30, 3, 0, 'Tıbbi Genetik ABD.', 'Division of Medical Genetics', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (726, 30, 3, 1, 'Tıbbi Genetik (Tezli Y.lisans)', 'Medical Genetics  (Master with Thesis)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (807, 19, 5, 3, 'İktisat (Y.Lisans Tezsiz)', 'Economics (Taught Master)', '1', 4, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (808, 19, 5, 4, 'İktisat (Y.Lisans Tezsiz)(İ.Ö.)', 'Economics (Taught Master) (SE)', '1', 4, 'tum', '0', '1');
INSERT INTO `birimler` VALUES (809, 19, 6, 0, 'Uluslararası ilişkiler ABD.', 'International Relations', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (810, 19, 6, 1, 'Uluslararası ilişkiler (Y.Lisans)', 'International Relations (Master)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (811, 19, 6, 2, 'Uluslararası ilişkiler (Doktora)', 'International Relations (PhD)', '1', 5, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (812, 19, 6, 3, 'Uluslararası ilişkiler-Ortadoğu Araştırmaları (Y.Lisans)', 'International Relations (Master)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (813, 19, 7, 0, 'Arkeoloji ABD.', 'Archaeology', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (814, 19, 7, 1, 'Arkeoloji (Y.Lisans)', 'Archaeology (Master)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (815, 19, 7, 2, 'Arkeoloji (Doktora)', 'Archaeology (PhD)', '1', 5, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (816, 19, 8, 0, 'Batı Dilleri Ve Edebiyatları ABD', 'Division of English Language and Literature', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (817, 19, 8, 1, 'İngiliz Dili ve Edebiyatı (Y.Lisans)', 'Division of English Language and Literature (Master)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (818, 19, 9, 0, 'Sanat Tarihi ABD', 'Art History', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (819, 19, 9, 1, 'Sanat Tarihi (Y.Lisans)', 'Art History (Master)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (820, 19, 9, 2, 'Sanat Tarihi (Doktora)', 'Art History (PhD)', '1', 5, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (821, 19, 10, 0, 'Tarih ABD.', 'History', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (822, 19, 10, 1, 'Tarih (Y.Lisans)', 'History (Master)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (823, 19, 11, 0, 'Coğrafya ABD.', 'Geography', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (824, 19, 11, 1, 'Coğrafya (Y.Lisans)', 'Geography (Master)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (825, 19, 11, 2, 'Coğrafya (Doktora)', 'Geography (PhD)', '1', 5, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (826, 19, 12, 0, 'Türk Dili ve Edebiyatı ABD.', 'Turkish Language & Literature', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (827, 19, 12, 1, 'Türk Dili ve Edebiyatı (Y.Lisans)', 'Turkish Language & Literature (Master)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (828, 19, 12, 2, 'Türk Dili ve Edebiyatı (Doktora)', 'Turkish Language & Literature (PhD)', '1', 5, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (829, 19, 13, 0, 'Felsefe ve Din Bilimleri ABD.', 'Philosophy & Religious Studies', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (830, 19, 13, 1, 'Felsefe ve Din Bilimleri (Y.Lisans)', 'Philosophy & Religious Studies (Master)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (831, 19, 13, 2, 'Felsefe ve Din Bilimleri (Doktora)', 'Philosophy & Religious Studies (PhD)', '1', 5, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (832, 19, 13, 3, 'Dinler Tarihi (Y.Lisans)', 'History of Religious (Master)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (833, 19, 14, 0, 'Resim ABD.', 'Painting', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (834, 19, 14, 1, 'Resim (Y.Lisans)', 'Painting (Master)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (835, 19, 15, 0, 'Seramik ABD.', 'Ceramics', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (836, 19, 15, 1, 'Seramik (Y.Lisans)', 'Ceramics (Master)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (837, 19, 16, 0, 'Temel İslam Bilimleri ABD.', 'Basic Islamic Studies', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (838, 19, 16, 1, 'Temel İslam Bilimleri (Y.Lisans)', 'Basic Islamic Studies (Master)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (839, 19, 16, 2, 'Temel İslam Bilimleri (Doktora)', 'Basic Islamic Studies (PhD)', '1', 5, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (840, 19, 16, 3, 'Hadis (Y.Lisans)', ' (Master)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (841, 19, 17, 0, 'Turizm İşletmeciliği ABD.', 'Tourism Management', '1', 2, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (842, 19, 17, 1, 'Turizm İşletmeciliği (Y.Lisans)', 'Tourism Management (Master)', '1', 3, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (843, 19, 17, 2, 'Turizm İşletmeciliği (Doktora)', 'Tourism Management (PhD)', '1', 5, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (844, 19, 17, 3, 'Turizm İşletmeciliği (Y.Lisans Tezsiz)', 'Tourism Management (Taught Master)', '1', 4, 'tum', '1', '0');
INSERT INTO `birimler` VALUES (845, 19, 17, 4, 'Turizm İşletmeciliği (Y.Lisans Tezsiz)(İ.Ö.)', 'Tourism Management (Taught Master) (S.E.)', '1', 4, 'tum', '1', '1');